export const implementedCalculatorList = [
  'personal-loan-emi',
  'home-loan-emi',
  'car-loan-emi',
  'education-loan-emi',
  'business-loan-emi',
  'gold-loan-emi',
  'two-wheeler-loan',
  'loan-prepayment-impact',
  'loan-eligibility',
  'loan-comparison',
  'simple-interest-loan',
  'compound-interest-loan',
  'loan-amortization',
  'remaining-loan-balance',
  'top-up-loan',
  'sip-calculator',
  'mutual-fund-returns',
  'cagr-calculator',
  'roi-calculator',
  'fd-calculator',
  'rd-calculator',
  'nps-calculator',
  'ppf-calculator',
  'retirement-corpus',
  'lumpsum-calculator',
  'inflation-impact',
  'compound-interest-investment',
  'income-tax-calculator',
  'salary-breakup',
  'hra-calculator',
  'pf-calculator',
  'gratuity-calculator',
  'tds-calculator',
  'gst-calculator',
  'professional-tax',
  'advance-tax-calculator',
  'post-tax-income',
  'currency-converter',
  'crypto-profit-loss',
  'forex-margin',
  'bitcoin-converter',
  'exchange-rate-impact',
  'import-export-duty',
  'gold-silver-price',
  'international-transfer',
  'savings-account-interest',
  'deposit-maturity',
  'interest-rate-comparison',
  'deposit-growth',
  'bank-charges',
  'atm-withdrawal-charges',
  'loan-against-fd',
  'money-market-calculator',
  'rd-planner',
  'profit-margin',
  'break-even-calculator',
  'discount-calculator',
  'roas-calculator',
  'working-capital',
  'markup-calculator',
  'commission-calculator',
  'tip-calculator',
  'age-calculator',
  'date-difference',
  'date-plus-duration',
  'percentage-calculator',
  'fuel-cost-calculator',
  'bmi-calculator',
  'bmr-calculator',
  'body-fat-calculator',
  'calorie-calculator',
  'ideal-weight-calculator',
  'macro-calculator',
  'tdee-calculator',
  'water-intake-calculator',
  'lean-body-mass',
  'waist-hip-ratio',
  'protein-calculator',
  'calories-burned',
  'target-heart-rate',
  'sleep-calculator',
  'body-surface-area',
  'waist-to-height-ratio',
  'waist-circumference',
  'neck-circumference',
  'hip-circumference',
  'integrated-health-dashboard',
  'body-adiposity-index',
  'ponderal-index',
  'a-body-shape-index-absi',
  'body-shape-index',
  'ffmi-calculator',
  'ideal-body-fat',
  'chest-waist-ratio',
  'arm-span-height-ratio',
  'mid-upper-arm-circumference',
  'calf-circumference',
  'meal-planner',
  'glycemic-index-calculator',
  'glycemic-load-calculator',

  // Business Tools (Actually Implemented - 8 tools)
  'profit-margin',
  'gross-profit-calculator',
  'net-profit-calculator',
  'break-even-calculator',
  'markup-calculator',
  'clv-calculator',
  'cac-calculator',
  'quick-ratio',
  'debt-to-equity',
  'pe-ratio',

  // Health Tools - Nutrition
  'fiber-intake-calculator',
  'sugar-intake-calculator',
  'sodium-intake-calculator',
  'fat-intake-calculator',
  'carb-calculator',
  'vitamin-d-calculator',
  'iron-intake-calculator',
  'hydration-electrolyte-calculator',
  'keto-macro-calculator',
  'intermittent-fasting-window',
  'meal-calorie-breakdown',
  'nutrition-label-calculator',
  'caffeine-half-life',
  'creatine-intake',
  'beta-alanine-dosage',
  'citrulline-malate',
  'bcaa-dosage',
  'eaa-dosage',
  'glutamine-dosage',
  'leucine-threshold',
  'casein-protein',
  'whey-protein',
  'plant-protein',
  'collagen-dosage',
  'electrolyte-balance',
  'post-bariatric-protein',
  'toddler-calorie',
  'pace-calculator',
  'one-rep-max',
  'vo2-max-calculator',
  'training-zone-calculator',
  'workout-intensity',
  'running-cadence-calculator',
  'stride-length-calculator',
  'running-distance-time',
  'cycling-pace-calculator',
  'met-calculator',
  'strength-volume-calculator',
  'workout-recovery-time',
  'heart-rate-reserve',
  'max-heart-rate-calculator',
  'lactate-threshold',
  'rpe-calculator',
  'calories-burned-walking',
  'calories-burned-running',
  'steps-to-calories',
  'blood-pressure-calculator',
  'resting-heart-rate',
  'cardiovascular-risk',
  'pulse-pressure-calculator',
  'mean-arterial-pressure',
  'heart-age-calculator',
  'blood-volume-calculator',
  'cardiac-output-calculator',
  'oxygen-saturation-interpreter',
  'respiration-rate-calculator',
  'hrv-score-calculator',
  'ankle-brachial-index',
  'dehydration-risk',
  'body-temperature-tracker',
  'blood-pressure-tracker',
  'resting-pulse-tracker',
  'stress-heart-impact',
  'vital-signs-summary',
  'hydration-vitals-estimator',
  'pregnancy-calculator',
  'due-date-calculator',
  'ovulation-calculator',
  'conception-calculator',
  'pregnancy-weight-gain',
  'fertility-window',
  'pregnancy-week-calculator',
  'trimester-calculator',
  'cycle-length-calculator',
  'period-tracker',
  'conception-window',
  'ivf-due-date-calculator',
  'pregnancy-calorie-calculator',
  'pregnancy-bmi-calculator',
  'fetal-growth-percentile',
  'baby-kick-counter',
  'contraction-timer',
  'breastfeeding-calorie',
  'pregnancy-appointment-schedule',
  'fertility-score-calculator',
  'sleep-cycle-calculator',
  'caffeine-calculator',
  'stress-level-calculator',
  'screen-time-calculator',
  'sleep-debt-calculator',
  'nap-calculator',
  'jet-lag-calculator',
  'circadian-rhythm-calculator',
  'blue-light-schedule',
  'meditation-timer',
  'breathing-exercise-timer',
  'alcohol-sleep-impact',
  'nicotine-sleep-impact',
  'daily-habit-score',
  'mindfulness-score',
  'burnout-risk-calculator',
  'hydration-reminder',
  'bedtime-reminder',
  'sleep-quality-score',
  'weight-loss-calculator',
  'calorie-deficit-calculator',
  'body-frame-calculator',
  'weight-goal-tracker',
  'maintenance-calorie-calculator',
  'weight-maintenance-planner',
  'bulk-cut-calculator',
  'body-recomposition-calculator',
  'weekly-calorie-budget',
  'goal-weight-date',
  'bmi-goal-tracker',
  'body-fat-goal-planner',
  'inch-loss-calculator',
  'weight-loss-percentage',
  'calorie-cycling',
  'cheat-meal-impact',
  'weight-plateau-calculator',
  'progress-checkin',
  'metabolism-tracker',
  'diabetes-risk-calculator',
  'cholesterol-ratio-calculator',
  'stroke-risk-calculator',
  'metabolic-syndrome-calculator',
  'bone-density-calculator',
  'kidney-function-calculator',
  'hypertension-risk-calculator',
  'sleep-apnea-risk-calculator',
  'fatty-liver-risk-calculator',
  'anemia-risk-calculator',
  'thyroid-risk-calculator',
  'insulin-resistance-homa-ir',
  'kidney-stone-risk',
  'liver-function-score',
  'immune-score-calculator',
  'vitamin-deficiency-check',
  'asthma-control-score',
  'allergy-symptom-score',
  'migraine-trigger-tracker',
  'inflammation-crp-interpreter',
  'thigh-circumference-measure',
  'forearm-circumference',
  'shoulder-width-calculator',
  'torso-length-measure',
  'leg-length-calculator',
  'sitting-height-ratio',
  'bmi-prime-calculator',
  'corpulence-index',
  'body-roundness-index',
  'conicity-index',
  'sagittal-abdominal-diameter',
  'wrist-circumference',
  'ankle-circumference',
  'bicep-circumference',
  'tricep-skinfold',
  'subscapular-skinfold',
  'suprailiac-skinfold',
  'abdominal-skinfold',
  'thigh-skinfold',
  'omega3-intake-calculator',
  'calcium-intake-calculator',
  'magnesium-intake',
  'potassium-intake',
  'zinc-intake-calculator',
  'vitamin-c-intake',
  'vitamin-b12-intake',
  'folate-intake-calculator',
  'protein-timing-calculator',
  'pre-workout-nutrition',
  'post-workout-nutrition',
  'meal-frequency-calculator',
  'portion-size-calculator',
  'micronutrient-tracker',
  'alcohol-calorie-calculator',
  'eating-window-16-8',
  'carb-cycling-planner',
  'paleo-macro-calculator',
  'vegan-protein-calculator',
  'nutrient-density-score',
  'swimming-calories-burned',
  'hiit-workout-calculator',
  'yoga-calories-calculator',
  'pilates-calorie-burn',
  'jump-rope-calculator',
  'rowing-calories-burned',
  'stair-climbing-calories',
  'elliptical-calories',
  'boxing-calories-burned',
  'dance-calories-calculator',
  'rock-climbing-calories',
  'tennis-calories-burned',
  'basketball-calories',
  'soccer-calories-burned',
  'golf-calories-calculator',
  'bench-press-calculator',
  'squat-strength-calculator',
  'deadlift-calculator',
  'wilks-score-calculator',
  'cooper-test-calculator',
  'qrs-duration-calculator',
  'qt-interval-calculator',
  'stroke-volume-calculator',
  'ejection-fraction-estimate',
  'cardiac-index-calculator',
  'systemic-vascular-resistance',
  'pulse-oximetry-tracker',
  'arterial-stiffness-index',
  'ventricular-rate-calculator',
  'atrial-fibrillation-rate',
  'pulse-deficit-calculator',
  'respiratory-quotient',
  'tidal-volume-calculator',
  'minute-ventilation',
  'alveolar-gas-equation',
  'aa-gradient-calculator',
  'pao2-fio2-ratio',
  'oxygen-delivery-calculator',
  'oxygen-consumption',
  'metabolic-cart-simulator',
  'luteal-phase-calculator',
  'follicular-phase-tracker',
  'cervical-mucus-tracker',
  'basal-body-temp-tracker',
  'pregnancy-test-timing',
  'hcg-doubling-calculator',
  'fundal-height-calculator',
  'pregnancy-blood-volume',
  'morning-sickness-tracker',
  'gestational-age-calculator',
  'naegeles-rule-calculator',
  'pregnancy-milestones',
  'amniotic-fluid-index',
  'biophysical-profile-score',
  'bishops-score-calculator',
  'apgar-score-calculator',
  'breastmilk-storage-guide',
  'newborn-feeding-schedule',
  'postpartum-recovery-tracker',
  'pms-symptom-tracker',
  'sleep-efficiency-calculator',
  'power-nap-timer',
  'polyphasic-sleep-planner',
  'shift-work-sleep-planner',
  'sleep-onset-latency',
  'wake-after-sleep-onset',
  'sleep-fragmentation-index',
  'chronotype-calculator',
  'social-jetlag-calculator',
  'melatonin-timing-calculator',
  'light-exposure-tracker',
  'darkness-exposure-planner',
  'exercise-sleep-timing',
  'dinner-bedtime-gap',
  'bedroom-temp-optimizer',
  'noise-sleep-impact',
  'weekend-sleep-calculator',
  'sleep-pressure-calculator',
  'adenosine-clearance',
  'sleep-hygiene-score',
  'weight-fluctuation-tracker',
  'body-measurement-tracker',
  'before-after-comparison',
  'progress-photo-planner',
  'weight-trend-analyzer',
  'refeed-day-calculator',
  'diet-break-planner',
  'reverse-diet-calculator',
  'adaptive-thermogenesis',
  'neat-calculator',
  'thermic-effect-food',
  'adaptive-tdee-calculator',
  'muscle-gain-predictor',
  'fat-loss-predictor',
  'skinny-fat-calculator',
  'genetic-potential-calculator',
  'ffmi-natural-limit',
  'water-weight-calculator',
  'glycogen-depletion',
  'framingham-risk-score',
  'ascvd-risk-calculator',
  'chads2-vasc-score',
  'has-bled-score',
  'wells-score-dvt',
  'wells-score-pe',
  'perc-rule-calculator',
  'curb-65-score',
  'sofa-score-calculator',
  'qsofa-score',
  'sirs-criteria-calculator',
  'apache-ii-score',
  'meld-score-calculator',
  'child-pugh-score',
  'egfr-calculator',
  'creatinine-clearance',
  'urine-protein-creatinine',
  'anion-gap-calculator',
  'corrected-calcium',
  'ldl-cholesterol-calculator',
  'basic-calculator',
  'fraction-calculator',
  'rent-vs-buy',
  'step-up-sip',
  'swp-calculator',
  'fire-calculator',
  'capital-gains-tax',
  'old-vs-new-regime',
  'credit-card-payoff',
  'ssy-calculator',
  'scss-calculator',

  // Math Calculators - Enhanced implementations via GenericMathTool
  'basic-calculator',
  'fraction-calculator',
  'percentage-calculator',
  'ten-percent-calculator',
  'twenty-percent-calculator',
  'ratio-calculator',
  'average-calculator',
  'square-root-calculator',
  'cube-root-calculator',
  'factorial-calculator',
  'absolute-value-calculator',
  'reciprocal-calculator',
  'rounding-calculator',
  'remainder-calculator',
  'modulo-calculator',
  'exponent-calculator',
  'logarithm-calculator',
  'gcd-calculator',
  'greatest-common-divisor',
  'lcm-calculator',
  'least-common-multiple',
  'prime-number-checker',
  'distance-formula-calculator',
  'midpoint-calculator',
  'slope-calculator',
  'quadratic-formula-calculator',
  'scientific-notation-calculator',
  'significant-figures-calculator',
  'arithmetic-progression-calculator',
  'geometric-progression-calculator',
  'pythagorean-theorem-calculator',
  'double-calculator',
  'triple-calculator',
  'half-calculator',
  'quarter-calculator',
  'third-calculator',
  'sum-of-series-calculator',
  'product-of-series-calculator',
  'area-calculator',

  // Physics Tools - Enhanced via GenericPhysicsTool
  'velocity-calculator',
  'force-calculator',
  'acceleration-calculator',
  'momentum-calculator',
  'projectile-motion',
  'friction-calculator',
  'torque-calculator',
  'centripetal-force',
  'free-fall-calculator',
  'gravitational-force',
  'density-calculator',
  'pressure-calculator',
  'buoyancy-calculator',
  'simple-pendulum',
  'impulse-calculator',
  'kinetic-energy',
  'potential-energy',
  'work-calculator',
  'mechanical-energy',
  'efficiency-calculator',
  'ohms-law',
  'power-consumption',
  'voltage-divider',
  'resistance-calculator',
  'capacitance-calculator',
  'current-divider',
  'led-resistor',
  'battery-capacity',
  'frequency-wavelength',

  // Everyday Life Tools - Priority 1 Implementation
  // Time & Productivity (13 tools)
  'pomodoro-timer-calculator',
  'time-zone-converter',
  'meeting-time-finder',
  'work-hours-calculator',
  'overtime-calculator',
  'break-time-calculator',
  'deadline-calculator',
  'age-calculator',
  'day-counter',
  'hour-to-day-converter',
  'shift-schedule-calculator',
  'time-card-calculator',
  'productivity-score-calculator',

  // Travel & Transportation (18 tools)
  'fuel-cost-calculator',
  'trip-cost-calculator',
  'mileage-tracker',
  'car-maintenance-cost',
  'toll-calculator',
  'parking-cost-calculator',
  'road-trip-planner',
  'flight-cost-comparison',
  'hotel-cost-calculator',
  'travel-budget-calculator',
  'distance-calculator',
  'eta-calculator',
  'cab-fare-estimator',
  'train-ticket-estimator',
  'bus-fare-calculator',
  'luggage-weight-calculator',
  'foreign-exchange-calculator',
  'travel-insurance-cost',

  // Home & Living (16 tools)
  'rent-vs-buy-calculator',
  'room-size-calculator',
  'paint-calculator',
  'tile-calculator',
  'wallpaper-calculator',
  'furniture-dimension-calculator',
  'moving-cost-calculator',
  'utility-bill-calculator',
  'water-bill-calculator',
  'electricity-bill-calculator',
  'gas-bill-calculator',
  'ac-power-consumption',
  'refrigerator-cost-calculator',
  'room-heater-cost',
  'carpet-area-calculator',
  'interior-design-budget',

  // Priority 2 Implementation
  // Mobile & Communication (10 tools)
  'data-plan-calculator',
  'call-cost-calculator',
  'sms-package-cost',
  'internet-speed-calculator',
  'wifi-coverage-calculator',
  'phone-bill-estimator',
  'roaming-charges-calculator',
  'mobile-insurance-calculator',
  'phone-upgrade-calculator',
  'prepaid-vs-postpaid',

  // Wedding & Events (10 tools)
  'wedding-budget-calculator',
  'guest-list-calculator',
  'venue-cost-calculator',
  'catering-cost-calculator',
  'decoration-budget',
  'invitation-cost-calculator',
  'photography-cost-calculator',
  'wedding-card-cost',
  'honeymoon-budget-calculator',
  'gift-registry-calculator',

  // Parenting & Baby (12 tools)
  'baby-due-date-calculator',
  'baby-growth-tracker',
  'diaper-cost-calculator',
  'baby-food-calculator',
  'baby-sleep-schedule',
  'vaccination-schedule-calculator',
  'child-education-cost-calculator',
  'daycare-cost-calculator',
  'baby-product-budget',
  'formula-milk-calculator',
  'baby-milestone-tracker',
  'baby-name-numerology',

  // Time Conversion (12 tools)
  'time-unit-converter', 'military-time-converter', 'unix-timestamp-converter', 'seconds-to-hms',
  'decimal-to-time', 'time-to-decimal', 'minutes-to-hours', 'hours-to-minutes',
  'days-to-hours', 'weeks-to-days', 'months-to-years', 'years-to-days',

  // Date Calculations (10 tools)
  'date-difference', 'date-add-subtract', 'workday-calculator', 'age-calculator',
  'leap-year-calculator', 'day-of-week', 'week-number', 'day-of-year',
  'quarter-calculator', 'business-days',

  // Work & Productivity (11 tools)
  'work-hours-calculator', 'timesheet-calculator', 'overtime-calculator', 'shift-calculator',
  'break-time-calculator', 'pomodoro-calculator', 'productivity-tracker', 'billable-hours',
  'time-tracking', 'lunch-break-optimizer', 'work-efficiency',

  // Event & Planning (10 tools)
  'countdown-calculator', 'anniversary-calculator', 'birthday-calculator', 'retirement-date',
  'pregnancy-due-date', 'wedding-countdown', 'exam-countdown', 'vacation-planner',
  'meeting-scheduler', 'deadline-tracker', 'xat-score-calculator',

  // Calendar & Year Tools (12 tools)
  'leap-year-calculator', 'week-number-calculator', 'calendar-generator', 'moon-phase-calculator',
  'solar-eclipse-calculator', 'lunar-calendar', 'hijri-calendar', 'hebrew-calendar',
  'chinese-calendar', 'julian-date', 'fiscal-year-calculator', 'academic-year-planner',

  // World Time & Zones (10 tools)
  'world-clock', 'time-zone-difference', 'ist-to-utc', 'utc-to-local',
  'gmt-converter', 'dst-calculator', 'international-meeting-time', 'time-zone-map',
  'sunrise-sunset', 'golden-hour-calculator',

  // Time Tracking & Management (10 tools)
  'time-spent-calculator', 'average-time-calculator', 'time-estimation', 'elapsed-time',
  'remaining-time', 'time-percentage', 'cumulative-time', 'time-log-analyzer',
  'daily-time-budget', 'weekly-time-planner',

  // Special Dates & Occasions (10 tools)
  'days-of-life', 'relationship-duration', 'job-tenure-calculator', 'sobriety-calculator',
  'smoke-free-calculator', 'fitness-streak', 'habit-tracker', 'memorial-date',
  'milestone-tracker', 'anniversary-reminder',

  // Biological & Health Time (10 tools)
  'pregnancy-week-calculator', 'conception-calculator', 'ovulation-calculator', 'menstrual-cycle',
  'fetal-development', 'vaccination-schedule', 'sleep-cycle-calculator', 'circadian-rhythm',
  'jet-lag-calculator', 'nap-time-optimizer',

  // Historical & Astronomical (10 tools)
  'historical-event-age', 'century-calculator', 'decade-calculator', 'era-converter',
  'sidereal-time', 'equinox-solstice', 'planet-position', 'zodiac-sign-calculator',
  'chinese-zodiac', 'vedic-panchang',

  // Time-Based Financial (10 tools)
  'hourly-to-annual', 'annual-to-hourly', 'pay-period-calculator', 'time-value-money',
  'compound-time', 'payroll-hours', 'time-off-accrual', 'sick-leave-calculator',
  'contract-duration', 'subscription-cost-time',
]

export const implementedCalculatorIds = new Set(implementedCalculatorList)
