steps:
  # Step 1: Build Docker image for Calculator Loop
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/calculatorloop:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/calculatorloop:latest'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: '3600s'
    id: 'build-image'

  # Step 2: Push image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/calculatorloop'
    timeout: '1800s'
    id: 'push-image'

# Images to be pushed to the registry
images:
  - 'gcr.io/$PROJECT_ID/calculatorloop:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/calculatorloop:latest'

timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
