name: Deploy CalculatorLoop

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} # ya key use karo
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/Calculatorloop || exit 1
            git pull origin main
            npm ci
            npm run build
            pm2 restart calculator-app || pm2 start npm --name "calculator-app" -- start
